sudo: false
language: node_js
node_js:
  - 'stable'
  - '8'
  - '6'
script:
  - npm run build
  - npm test
before_deploy:
  - ls -lh a.json b.json c.json
  - npm i semver
  - npm version --no-git-tag-version --force $(./node_modules/.bin/semver -i minor $(npm info vbb-fare-zones version))
deploy:
  provider: npm
  on:
    branch: master
    node: 'stable'
  email: 'mail@jannisr.de'
  api_key: ${NPM_KEY}
  skip_cleanup: true
